### PR TITLE
MWUTUASSIN-7 : Ignores deleted users that were assigned to an unit

### PR DESCRIPTION
**Pull request by glepine1**

### CODE REVIEW

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by glepine1** [comment]
rerun

**Comment by ryahiaoui** [comment]
rerun

**Pull request merged**
